AWSTemplateFormatVersion: 2010-09-09
Description: c2c task definition and service and logging
Resources:

  UILogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: c2c-ui

  APILogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: c2c-api

  PredictionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: c2c-ml

  PostgresLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: c2c-postgres

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue c2c-alb-listenerarn
      Priority: 1
      Actions:
        - Type: forward
          TargetGroupArn: !ImportValue c2c-alb-defaulttargetgrouparn
      Conditions:
        - Field: path-pattern
          Values:
            - /

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: c2c
      ContainerDefinitions:
        - Name: c2c-ui
          Image: 113913174193.dkr.ecr.us-east-1.amazonaws.com/c2c-ui:latest
          MemoryReservation: 256
          Essential: true
          Command:
            - npm run dev
          PortMappings:
            - ContainerPort: 8000
              HostPort: 0
          Links:
            - c2c-api
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: us-east-1
              awslogs-group: !Ref UILogGroup
        - Name: c2c-api
          Image: 113913174193.dkr.ecr.us-east-1.amazonaws.com/c2c-api:latest
          MemoryReservation: 256
          Essential: true
          Environment:
            - Name: POSTGRES_USER
              Value: concepttoclinic
            - Name: USE_DOCKER
              Value: yes
            - Name: SECRET_KEY
              Value: notverysecret
            - Name: DEBUG
              Value: "True"
            - Name: DJANGO_SETTINGS_MODULE
              Value: config.settings.local
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: us-east-1
              awslogs-group: !Ref APILogGroup
        - Name: c2c-prediction
          Image: 113913174193.dkr.ecr.us-east-1.amazonaws.com/c2c-prediction
          MemoryReservation: 256
          Essential: true
          Command:
            - flask run --host=0.0.0.0 --port=8001
          Environment:
            - Name: FLASK_DEBUG
              Value: 1
            - Name: FLASK_APP
              Value: src/factory.py
            - Name: LC_ALL
              Value: C.UTF-8
            - Name: LANG
              Value: C.UTF-8
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: us-east-1
              awslogs-group: !Ref PredictionLogGroup
        - Name: c2c-postgres
          Image: postgres:9.6
          MemoryReservation: 256
          Essential: true
          Environment:
            - Name: POSTGRES_USER
              Value: concepttoclinic
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: us-east-1
              awslogs-group: !Ref PostgresLogGroup

  Service:
    Type: AWS::ECS::Service
    Properties:
      Role:  arn:aws:iam::113913174193:role/concept-to-clinic-ecs-service-role
      PlacementStrategies:
        - Type: spread
          Field: instanceId
      Cluster: c2c
      DesiredCount: 2
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - TargetGroupArn: !ImportValue c2c-alb-defaulttargetgrouparn
          ContainerPort: 8000
          ContainerName: c2c-ui

  HealthHostsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Healthy host alarm for c2c
      AlarmName: c2c-healthyhosts
      MetricName: HealthyHostCount
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 1
      Dimensions:
        - Name: LoadBalancer
          Value: !ImportValue c2c-alb-loadbalancerfullname
        - Name: TargetGroup
          Value: !ImportValue c2c-alb-defaulttargetgroupfullname
      Namespace: AWS/ApplicationELB
      Period: 60
      Statistic: Maximum
      Threshold: 2
