AWSTemplateFormatVersion: 2010-09-09
Description: c2c task definition and service
Resources:
  
  UILogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: c2c-ui

  APILogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: c2c-api

  MLLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: c2c-ml

  PostgresLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: c2c-postgres

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn:
        Fn::ImportValue:
          !Sub ${TeamName}-alb-${Environment}-listenerarn
      Priority: !Ref ListenerPriority
      Actions:
        - Type: forward
          TargetGroupArn:
            Fn::ImportValue:
              !Sub ${TeamName}-alb-${Environment}-defaulttargetgrouparn
      Conditions:
        - Field: path-pattern
          Values:
            - !Sub ${ListenerPath}

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !Ref TaskRoleArn
      Family: !Sub ${TeamName}-${Application}-${Environment}
      ContainerDefinitions:
        - Name: c2c-ui
          Image: !Sub ${Image}:${ImageVersion}
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: us-east-1
              awslogs-group: !Ref UILogGroup
        - Name: c2c-api
          Image:
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: us-east-1
              awslogs-group: !Ref APILogGroup
        - Name: c2c-ml
          Image:
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: us-east-1
              awslogs-group: !Ref MLLogGroup
        - Name: c2c-postgres
          Image:
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: us-east-1
              awslogs-group: !Ref PostgresLogGroup

  Service:
    Type: AWS::ECS::Service
    Properties:
      Role: !Ref ECSServiceRole
      PlacementStrategies:
        - Type: spread
          Field: instanceId
      Cluster: c2c
      DesiredCount: 2
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - TargetGroupArn:
            Fn::ImportValue:
              !Sub ${TeamName}-alb-${Environment}-defaulttargetgrouparn
          ContainerPort: 443
          ContainerName: c2c-ui

  HealthHostsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: !Sub Healthy host alarm for ${Application}
      AlarmName: !Sub ${TeamName}-${Environment}-${Application}-healthyhosts
      MetricName: HealthyHostCount
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 1
      Dimensions:
        - Name: LoadBalancer
          Value:
            Fn::ImportValue:
              !Sub ${TeamName}-alb-${Environment}-loadbalancerfullname
        - Name: TargetGroup
          Value: !GetAtt TargetGroup.TargetGroupFullName
      Namespace: AWS/ApplicationELB
      Period: 60
      Statistic: Maximum
      Threshold: !Ref DesiredCount
