---
- hosts: localhost
  tasks:
  - name: create ECS cluster
    cloudformation:
      stack_name: c2c-ecs
      state: present
      region: us-east-1
      changeset_name: c2c-ecs
      create_changeset: true
      template: "../templates/ecs.yml"
