---
- hosts: localhost
  tasks:
  - name: create ECS Service
    cloudformation:
      stack_name: c2c-service
      state: present
      region:
      changeset_name: c2c-service
      create_changeset: true
      template: "../templates/service.yml"
